from sqlmodel import create_engine, SQLModel, Session
from pydantic_settings import BaseSettings, SettingsConfigDict
from typing import Optional


class Settings(BaseSettings):
    """Configurações da aplicação via variáveis de ambiente."""
    database_url: str = "postgresql://zemarques:mrq831028@db:5432/estoque-db"
    jwt_secret: str = "eletrosil-super-secret-key-change-in-production"

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )


settings = Settings()

engine = create_engine(
    settings.database_url,
    echo=False,
    pool_size=5,
    max_overflow=10,
)


def get_session():
    """Provedor de sessão do SQLModel para injeção de dependência no FastAPI."""
    with Session(engine) as session:
        yield session


def init_db():
    """Cria as tabelas no banco (usado apenas em desenvolvimento)."""
    SQLModel.metadata.create_all(engine)

    # Migrações incrementais
    _run_migrations()


def _run_migrations():
    """Executa migrações manuais para tabelas existentes."""
    from sqlmodel import text

    with engine.connect() as conn:
        # Migração 1: adicionar receipt_number à tabela sales
        result = conn.execute(
            text(
                "SELECT column_name FROM information_schema.columns "
                "WHERE table_name='sales' AND column_name='receipt_number'"
            )
        )
        if not result.fetchone():
            conn.execute(
                text(
                    "ALTER TABLE sales "
                    "ADD COLUMN receipt_number INTEGER "
                    "GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1);"
                )
            )
            conn.commit()
            print("[migration] Coluna sales.receipt_number adicionada com sucesso!")
        else:
            print("[migration] Coluna sales.receipt_number já existe.")

        # Migração 2: adicionar role à tabela users (RBAC Sprint 8)
        result = conn.execute(
            text(
                "SELECT column_name FROM information_schema.columns "
                "WHERE table_name='users' AND column_name='role'"
            )
        )
        if not result.fetchone():
            conn.execute(
                text(
                    "ALTER TABLE users "
                    "ADD COLUMN role VARCHAR NOT NULL DEFAULT 'operator';"
                )
            )
            # Sincroniza role dos admins existentes
            conn.execute(
                text(
                    "UPDATE users SET role = 'admin' "
                    "WHERE is_admin = TRUE AND role = 'operator';"
                )
            )
            conn.commit()
            print("[migration] Coluna users.role adicionada e sincronizada com sucesso!")
        else:
            print("[migration] Coluna users.role já existe.")

        # Migração 3: adicionar commission_rate à tabela users
        result = conn.execute(
            text(
                "SELECT column_name FROM information_schema.columns "
                "WHERE table_name='users' AND column_name='commission_rate'"
            )
        )
        if not result.fetchone():
            conn.execute(
                text(
                    "ALTER TABLE users "
                    "ADD COLUMN commission_rate FLOAT NOT NULL DEFAULT 0.0;"
                )
            )
            conn.commit()
            print("[migration] Coluna users.commission_rate adicionada com sucesso!")
        else:
            print("[migration] Coluna users.commission_rate já existe.")

        # Migração 4: adicionar seller_id à tabela sales
        result = conn.execute(
            text(
                "SELECT column_name FROM information_schema.columns "
                "WHERE table_name='sales' AND column_name='seller_id'"
            )
        )
        if not result.fetchone():
            conn.execute(
                text(
                    "ALTER TABLE sales "
                    "ADD COLUMN seller_id UUID REFERENCES users(id);"
                )
            )
            conn.commit()
            print("[migration] Coluna sales.seller_id adicionada com sucesso!")
        else:
            print("[migration] Coluna sales.seller_id já existe.")

        # Migração 5: adicionar commission_value à tabela sales
        result = conn.execute(
            text(
                "SELECT column_name FROM information_schema.columns "
                "WHERE table_name='sales' AND column_name='commission_value'"
            )
        )
        if not result.fetchone():
            conn.execute(
                text(
                    "ALTER TABLE sales "
                    "ADD COLUMN commission_value DECIMAL(12,2) NOT NULL DEFAULT 0.0;"
                )
            )
            conn.commit()
            print("[migration] Coluna sales.commission_value adicionada com sucesso!")
        else:
            print("[migration] Coluna sales.commission_value já existe.")

        # Migração 6: Criar índice para seller_id em sales
        result = conn.execute(
            text(
                "SELECT indexname FROM pg_indexes "
                "WHERE tablename='sales' AND indexname='ix_sales_seller_id'"
            )
        )
        if not result.fetchone():
            conn.execute(
                text("CREATE INDEX ix_sales_seller_id ON sales(seller_id);")
            )
            conn.commit()
            print("[migration] Índice ix_sales_seller_id criado com sucesso!")
        else:
            print("[migration] Índice ix_sales_seller_id já existe.")

        conn.close()
