"""Script para adicionar a coluna receipt_number à tabela sales."""
from app.core.database import engine
from sqlmodel import text

def run():
    with engine.connect() as conn:
        # Verifica se a coluna já existe
        result = conn.execute(
            text("SELECT column_name FROM information_schema.columns WHERE table_name='sales' AND column_name='receipt_number'")
        )
        if result.fetchone():
            print("Coluna receipt_number já existe. Nada a fazer.")
            return

        # Adiciona a coluna com IDENTITY (auto-increment)
        conn.execute(
            text(
                "ALTER TABLE sales "
                "ADD COLUMN receipt_number INTEGER "
                "GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1);"
            )
        )
        conn.commit()
        print("Coluna receipt_number adicionada com sucesso!")

if __name__ == "__main__":
    run()
