name: Local Config
version: 1.0.0
schema: v1
models:
  - name: DeepSeek Reasoner
    provider: deepseek
    model: deepseek-reasoner
    apiKey: sk-5bb30af0d1444792a33f171ae52b96ff
  - name: DeepSeek Chat
    provider: deepseek
    model: deepseek-chat
    apiKey: sk-5bb30af0d1444792a33f171ae52b96ff
    