"""
Configurações de Banco de Dados — Eletrosil.

Timezone é forçado a America/Sao_Paulo em CADA sessão, garantindo
que todas as queries usem horário BR independente do servidor.
"""
from sqlmodel import create_engine, SQLModel, Session
from pydantic_settings import BaseSettings, SettingsConfigDict
from typing import Optional
from sqlmodel import text


class Settings(BaseSettings):
    """Configurações da aplicação via variáveis de ambiente."""
    database_url: str = ""
    jwt_secret: str = "eletrosil-super-secret-key-change-in-production"
    company_name: str = ""

    db_user: str = ""
    db_pass: str = ""
    db_host: str = ""
    db_port: str = "5432"
    db_name: str = ""

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    @property
    def resolved_database_url(self) -> str:
        if self.database_url:
            return self.database_url
        user = self.db_user
        password = self.db_pass
        host = self.db_host
        port = self.db_port
        name = self.db_name
        if not all([user, password, host, name]):
            raise ValueError(
                "Nenhuma DATABASE_URL fornecida e componentes DB_* incompletos."
            )
        return f"postgresql://{user}:{password}@{host}:{port}/{name}"


settings = Settings()
_database_url = settings.resolved_database_url

engine = create_engine(
    _database_url,
    echo=False,
    pool_size=5,
    max_overflow=10,
)


def get_session():
    """
    Provedor de sessão SQLModel.

    ═══════════════════════════════════════════════════════════════════════════
    TIMEZONE: FORÇA America/Sao_Paulo EM TODA SESSÃO
    ═══════════════════════════════════════════════════════════════════════════
    Isso garante que qualquer query SQL que dependa de timezone (NOW(),
    LOCALTIMESTAMP, etc.) use o horário brasileiro, independentemente do
    fuso configurado no servidor ou container.
    """
    with Session(engine) as session:
        session.exec(text("SET TIME ZONE 'America/Sao_Paulo';"))
        yield session


def init_db():
    """Cria tabelas e executa migrações mínimas."""
    SQLModel.metadata.create_all(engine)
    _run_migrations()


def _run_migrations():
    """
    Migrações automáticas.

    ⚠️  A MIGRAÇÃO DA UNIQUE CONSTRAINT EM customers.cpf_cnpj NÃO É FEITA AQUI.
    A experiência mostrou que migrações DDL automáticas via Python são frágeis
    e podem falhar silenciosamente (transações, erros de constraint, etc.).

    Para aplicar a constraint no banco, execute manualmente:
        docker exec -i postgres psql -U zemarques -d estoque-db < backend/migration_fisica.sql
    """
    with engine.connect() as conn:
        # ── Migração 1: receipt_number na sales ──
        result = conn.execute(text(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_name='sales' AND column_name='receipt_number'"
        ))
        if not result.fetchone():
            conn.execute(text(
                "ALTER TABLE sales "
                "ADD COLUMN receipt_number INTEGER "
                "GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1);"
            ))
            conn.commit()
            print("[migration] ✅ sales.receipt_number adicionada")

        # ── Migração 2: role na users ──
        result = conn.execute(text(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_name='users' AND column_name='role'"
        ))
        if not result.fetchone():
            conn.execute(text("ALTER TABLE users ADD COLUMN role VARCHAR NOT NULL DEFAULT 'operator';"))
            conn.execute(text("UPDATE users SET role = 'admin' WHERE is_admin = TRUE AND role = 'operator';"))
            conn.commit()
            print("[migration] ✅ users.role adicionada")

        # ── Migração 3: description e transfer_id na moves ──
        result = conn.execute(text(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_name='moves' AND column_name='description'"
        ))
        if not result.fetchone():
            conn.execute(text("ALTER TABLE moves ADD COLUMN description VARCHAR(255);"))
            conn.execute(text("ALTER TABLE moves ADD COLUMN transfer_id UUID;"))
            conn.execute(text("CREATE INDEX IF NOT EXISTS idx_moves_transfer_id ON moves(transfer_id);"))
            conn.commit()
            print("[migration] ✅ moves.description e moves.transfer_id adicionadas")

        # ── Migração 4: UNIQUE constraint em customers.cpf_cnpj ──
        # Apenas verifica e orienta o usuário a executar manualmente
        result = conn.execute(text(
            "SELECT conname FROM pg_constraint "
            "WHERE conrelid = 'customers'::regclass "
            "AND conname = 'unique_cpf_cnpj'"
        ))
        if result.fetchone():
            print("[migration] ✅ UNIQUE unique_cpf_cnpj OK")
        else:
            print("[migration] ⚠️  UNIQUE unique_cpf_cnpj AUSENTE!")
            print("[migration] ⚠️  Execute: docker exec -i postgres psql -U zemarques -d estoque-db < backend/migration_fisica.sql")

        # ── Migração 5: commission_rate na users ──
        result = conn.execute(text(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_name='users' AND column_name='commission_rate'"
        ))
        if not result.fetchone():
            conn.execute(text(
                "ALTER TABLE users ADD COLUMN commission_rate FLOAT NOT NULL DEFAULT 0.0;"
            ))
            conn.commit()
            print("[migration] ✅ users.commission_rate adicionada")

        # ── Migração 6: seller_id na sales ──
        result = conn.execute(text(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_name='sales' AND column_name='seller_id'"
        ))
        if not result.fetchone():
            conn.execute(text(
                "ALTER TABLE sales ADD COLUMN seller_id UUID REFERENCES users(id);"
            ))
            conn.commit()
            print("[migration] ✅ sales.seller_id adicionada")

        # ── Migração 7: commission_value na sales ──
        result = conn.execute(text(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_name='sales' AND column_name='commission_value'"
        ))
        if not result.fetchone():
            conn.execute(text(
                "ALTER TABLE sales ADD COLUMN commission_value DECIMAL(12,2) NOT NULL DEFAULT 0.0;"
            ))
            conn.commit()
            print("[migration] ✅ sales.commission_value adicionada")

        # ── Migração 8: Índice para seller_id na sales ──
        result = conn.execute(text(
            "SELECT indexname FROM pg_indexes "
            "WHERE tablename='sales' AND indexname='ix_sales_seller_id'"
        ))
        if not result.fetchone():
            conn.execute(text("CREATE INDEX ix_sales_seller_id ON sales(seller_id);"))
            conn.commit()
            print("[migration] ✅ ix_sales_seller_id criado")

        # ── Migração 9: Tabela quotes ──
        conn.execute(text(
            "SELECT to_regclass('quotes'::text);"
        ))
        result = conn.execute(text("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = 'quotes'
            )
        """))
        if not result.fetchone()[0]:
            conn.execute(text("""
                CREATE TABLE quotes (
                    id UUID PRIMARY KEY,
                    branch_id UUID NOT NULL REFERENCES branches(id),
                    user_id UUID NOT NULL REFERENCES users(id),
                    customer_id UUID REFERENCES customers(id),
                    seller_id UUID REFERENCES users(id),
                    gross_value DECIMAL(12,2) NOT NULL,
                    discount DECIMAL(12,2) NOT NULL DEFAULT 0,
                    total_value DECIMAL(12,2) NOT NULL,
                    status VARCHAR NOT NULL DEFAULT 'pendente',
                    expires_at TIMESTAMP NOT NULL,
                    observations TEXT,
                    created_at TIMESTAMP DEFAULT NOW(),
                    updated_at TIMESTAMP DEFAULT NOW()
                );
                CREATE TABLE quote_items (
                    id UUID PRIMARY KEY,
                    quote_id UUID NOT NULL REFERENCES quotes(id),
                    product_id UUID NOT NULL REFERENCES products(id),
                    product_name VARCHAR(255),
                    quantity INTEGER NOT NULL,
                    unit_price DECIMAL(12,2) NOT NULL,
                    subtotal DECIMAL(12,2) NOT NULL
                );
                CREATE INDEX idx_quotes_status ON quotes(status);
                CREATE INDEX idx_quotes_seller_id ON quotes(seller_id);
                CREATE INDEX idx_quotes_branch_id ON quotes(branch_id);
                CREATE INDEX idx_quote_items_quote_id ON quote_items(quote_id);
            """))
            conn.commit()
            print("[migration] ✅ Tabelas quotes e quote_items criadas")
        else:
            print("[migration] ✅ quotes e quote_items já existem")

        conn.close()
